name: "MP0"
semester: "Fall2018"
version: 1.0.0
grading:
  timeout: PT5M
  run: "./gradlew grade -Pgrade.capture -Pgrade.secure -Pgrade.reporting.file={{ gradeFile }}"
  ignoreOutput:
    - "^java.security.policy: error parsing file.*"
    - "^Unable to initialize policy entry:.*"
    - "^.*?expected \\[\\;\\], found \\[priority\\]$"
    - "^WARNING: An illegal reflective access operation has occurred.*"
    - "^WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass.*"
    - "^WARNING: Please consider reporting this to the maintainers.*"
    - "^WARNING: Use --illegal-access=warn to enable warnings.*"
    - "^WARNING: All illegal access operations will be denied in a future release.*"
    - "^The TaskInternal.*"
scoring:
  max: 100
  selectors:
    - checkstyle
    - test
forceCommitAfterPoints: true
vcs:
  git: true
students:
  location: email.txt
  require: true
  count: 1
  suffix: "@illinois.edu"
files:
  - "LCM"
  - "MinimumOfFirstN"
  - "Quizzer"
secure: config/security.policy
reporting:
  post: "https://cs125-reporting.cs.illinois.edu/progress"
checkstyle:
  name: "checkstyle Tests"
  missing:
    score: 0
    message: "checkstyle failed to run"
    name: "checkstyle"
  selectors:
    - selector: "count(//file/error) = 0"
      score: 10
      message: "No checkstyle errors were reported"
      name: "checkstyle"
    - selector: "count(//file/error) > 0"
      score: 0
      message: "checkstyle errors were reported"
      name: "checkstyle"
test:
  name: "testNG Tests"
  selectors:
    - selector: "count(//testcase[@name='gradeLCM']) = 1 and count(//testcase[@name='gradeLCM']//failure) = 0"
      score: 30
      message: "No test failures in LCM"
      name: "LCM"
    - selector: "count(//testcase[@name='gradeLCM']) = 1 and count(//testcase[@name='gradeLCM']//failure) > 0"
      score: 10
      message: "Test failures in LCM"
      name: "LCM"
    - selector: "count(//testcase[@name='gradeLCM']) = 0"
      score: 0
      message: "LCM didn't compile"
      name: "LCM"
    - selector: "count(//testcase[@name='gradeMinimumOfFirstN']) = 1 and count(//testcase[@name='gradeMinimumOfFirstN']//failure) = 0"
      score: 30
      message: "No test failures in MinimumOfFirstN"
      name: "MinimumOfFirstN"
    - selector: "count(//testcase[@name='gradeMinimumOfFirstN']) = 1 and count(//testcase[@name='gradeMinimumOfFirstN']//failure) > 0"
      score: 10
      message: "Test failures in MinimumOfFirstN"
      name: "MinimumOfFirstN"
    - selector: "count(//testcase[@name='gradeMinimumOfFirstN']) = 0"
      score: 0
      message: "MinimumOfFirstN didn't compile"
      name: "MinimumOfFirstN"
    - selector: "count(//testcase[@name='gradeQuizzer']) = 1 and count(//testcase[@name='gradeQuizzer']//failure) = 0"
      score: 30
      message: "No test failures in Quizzer"
      name: "Quizzer"
    - selector: "count(//testcase[@name='gradeQuizzer']) = 1 and count(//testcase[@name='gradeQuizzer']//failure) > 0"
      score: 10
      message: "Test failures in Quizzer"
      name: "Quizzer"
    - selector: "count(//testcase[@name='gradeQuizzer']) = 0"
      score: 0
      message: "Quizzer didn't compile"
      name: "Quizzer"

# vim: ts=2:sw=2:et
